In [3]:
my_list = [1,2,3]

In [1]:
import numpy as np

In [6]:
arr = np.array(my_list)

In [10]:
my_mat = [[1,2,3], [4,5,6],[7,8,9]]

In [12]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [17]:
np.zeros(3)

array([0., 0., 0.])

In [22]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones(4)

array([1., 1., 1., 1.])

In [32]:
np.linspace(0,5,8)

array([0.        , 0.71428571, 1.42857143, 2.14285714, 2.85714286,
       3.57142857, 4.28571429, 5.        ])

In [36]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [39]:
np.random.rand(5)

array([0.95230596, 0.54947579, 0.78153374, 0.76530643, 0.41846008])

In [41]:
np.random.rand(5,5)

array([[0.99256478, 0.54548005, 0.43262583, 0.63708063, 0.93013729],
       [0.95684176, 0.51000565, 0.19220055, 0.96965066, 0.901203  ],
       [0.46216739, 0.81547061, 0.54163853, 0.63792423, 0.16886686],
       [0.27862966, 0.31779705, 0.65163381, 0.34192066, 0.57006903],
       [0.06437667, 0.93274262, 0.45873723, 0.49458114, 0.18105302]])

In [44]:
np.random.randn(5,5)

array([[ 0.6933351 , -0.12109601, -0.04807656, -0.35701274, -1.51685058],
       [ 1.06867744,  0.36003528, -0.54585935, -0.72545363, -0.03913752],
       [-2.39556474,  1.86229385,  0.24388384,  0.1532944 ,  0.20082731],
       [-0.43256302, -0.03465091,  1.57199925, -0.98348811, -0.00706179],
       [-0.5220391 ,  1.87342309,  0.88956567,  0.05828437,  0.47081342]])