In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
my_mat = [[1,2,3], [4,5,6],[7,8,9]]

In [ ]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones(4)

array([1., 1., 1., 1.])

In [10]:
np.linspace(0,5,8)

array([0.        , 0.71428571, 1.42857143, 2.14285714, 2.85714286,
       3.57142857, 4.28571429, 5.        ])

In [11]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [12]:
np.random.rand(5)

array([0.17096375, 0.73402437, 0.73476599, 0.80594696, 0.81158978])

In [13]:
np.random.rand(5,5)

array([[0.23109955, 0.58116379, 0.34832744, 0.19661066, 0.93476806],
       [0.04766635, 0.14798627, 0.65727872, 0.45308621, 0.1126629 ],
       [0.78144393, 0.34681979, 0.79468415, 0.42837087, 0.00831818],
       [0.06968026, 0.16325927, 0.28383999, 0.577395  , 0.11932072],
       [0.83703777, 0.8211695 , 0.5174187 , 0.96251175, 0.61755499]])

In [14]:
np.random.randn(5,5)

array([[-0.05186587, -0.56467905, -0.49412933, -0.73453758, -0.10627134],
       [-1.0239181 ,  0.12176446,  1.32359687,  0.91810239, -0.62434233],
       [ 0.48487969, -1.03688507, -0.2630106 , -0.97741774, -0.28888848],
       [-1.96478646,  0.18732569, -1.10675005, -1.31674402,  0.89304075],
       [ 0.82829056, -0.73168604,  0.051724  ,  1.2804205 ,  0.4683156 ]])

In [15]:
np.random.randint(1,100,100)

array([19, 57, 49, 90,  5, 59, 40,  4,  4, 16, 92, 20, 71, 17, 71, 72, 89,
       50, 64, 96, 14,  4, 33, 22, 89, 45, 64, 87, 38, 92, 20, 97, 57, 25,
       60, 21, 73, 36, 65, 95, 89, 11, 43, 71, 51, 21, 18, 19, 58, 51,  3,
       40, 89, 86, 19, 37, 57, 90, 84, 63, 74, 18, 37, 66, 43, 78, 60, 18,
       78, 60, 20, 77, 77, 70, 17, 25, 33, 94, 86, 84, 20, 39, 64, 91, 69,
       46, 25, 27, 85, 98, 22, 52, 61,  4, 32, 71, 86, 32, 79, 32])

In [16]:
arr = np.arange(25)

In [17]:
ranarr = np.random.randint(0,50,10)

In [18]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
ranarr.max()

np.int64(46)

In [20]:
ranarr.min()

np.int64(14)

In [21]:
ranarr.argmax()

np.int64(9)

In [22]:
ranarr.dtype

dtype('int64')

In [23]:
arr = np.arange(0,11)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
arr[8]

np.int64(8)

In [26]:
arr[1:5]

array([1, 2, 3, 4])

In [27]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [28]:
arr[0:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
arr[0:5] = 100

In [30]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [31]:
slice_of_arr = arr[0:6]

In [32]:
slice_of_arr


array([100, 100, 100, 100, 100,   5])

In [33]:
slice_of_arr[:] = 99

In [34]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [35]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [36]:
arr_copy = arr.copy()

In [37]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [38]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [39]:
arr_copy[:] = 100

In [40]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [41]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [42]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [43]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [44]:
arr_2d[0][0]

np.int64(5)

In [45]:
arr_2d[0,0]

np.int64(5)

In [46]:
arr_2d[0]

array([ 5, 10, 15])

In [47]:
arr_2d[2][1]

np.int64(40)

In [48]:
arr_2d[1,2]

np.int64(30)

In [49]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [50]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [51]:
arr_2d[1:2,:]

array([[20, 25, 30]])

In [52]:
arr_2d[2:,]

array([[35, 40, 45]])

In [53]:
arr = np.arange(1,11)

In [54]:
bool_arr = arr > 5

In [55]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [56]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [57]:
arr[arr<3]

array([1, 2])

In [58]:
arr_2d = np.arange(50).reshape(5,10)

In [59]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [61]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [63]:
arr = np.arange(0,11)

In [65]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [69]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [71]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [73]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [75]:
arr/0

/tmp/ipykernel_1198/4291252909.py:1: RuntimeWarning: divide by zero encountered in divide
  arr/0
/tmp/ipykernel_1198/4291252909.py:1: RuntimeWarning: invalid value encountered in divide
  arr/0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [77]:
arr/arr

/tmp/ipykernel_1198/1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [79]:
1/arr

/tmp/ipykernel_1198/255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])