In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
my_mat = [[1,2,3], [4,5,6],[7,8,9]]

In [5]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones(4)

array([1., 1., 1., 1.])

In [10]:
np.linspace(0,5,8)

array([0.        , 0.71428571, 1.42857143, 2.14285714, 2.85714286,
       3.57142857, 4.28571429, 5.        ])

In [11]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [12]:
np.random.rand(5)

array([0.86847917, 0.29282385, 0.1685    , 0.55194149, 0.71856572])

In [13]:
np.random.rand(5,5)

array([[0.05128805, 0.85539336, 0.3493104 , 0.0264167 , 0.29237931],
       [0.29278707, 0.66557463, 0.13796306, 0.73734641, 0.87615378],
       [0.57764528, 0.32322754, 0.86328017, 0.81623119, 0.29199715],
       [0.42029676, 0.25043552, 0.91696839, 0.27873597, 0.90348952],
       [0.19050344, 0.47582713, 0.41861959, 0.74067953, 0.19170441]])

In [14]:
np.random.randn(5,5)

array([[ 0.14860515, -1.84486426,  0.22746807, -0.71269612,  1.28248315],
       [ 0.33496365, -0.59376728, -0.08824462, -0.38854863, -0.50856614],
       [-0.23736327,  0.26733876,  0.56022283, -0.29099064,  0.24546328],
       [-0.83272185, -0.54826822, -1.40646454,  0.18654345,  0.436461  ],
       [ 0.26716672,  0.20755913, -0.37649817,  0.35975115,  1.19765933]])

In [15]:
np.random.randint(1,100,100)

array([83, 44, 79, 48, 83, 97, 68, 73,  6, 59, 12, 21, 88, 36, 83, 41, 12,
       77, 47, 11, 99, 62, 70, 86, 53, 98, 98,  8, 55, 49, 85, 94, 96, 89,
       51,  8, 29, 54, 90, 39, 38,  9, 36, 64, 59, 40, 43, 17, 76, 45, 53,
       44, 99, 43, 85, 65, 72, 72, 79, 34, 68, 53, 27,  7, 78, 39, 34, 67,
       11, 90, 35, 57, 69, 29, 94, 28, 91, 69, 49, 24, 51,  6, 67, 73, 10,
       14, 53, 32, 39, 78, 30,  1, 56, 94, 91, 58, 83,  6, 64, 28])

In [16]:
arr = np.arange(25)

In [17]:
ranarr = np.random.randint(0,50,10)

In [18]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
ranarr.max()

np.int64(49)

In [20]:
ranarr.min()

np.int64(16)

In [21]:
ranarr.argmax()

np.int64(7)

In [22]:
ranarr.dtype

dtype('int64')

In [41]:
arr = np.arange(0,11)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr[8]

np.int64(8)

In [30]:
arr[1:5]

array([1, 2, 3, 4])

In [33]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [37]:
arr[0:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr[0:5] = 100

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
slice_of_arr = arr[0:6]

In [49]:
slice_of_arr


array([0, 1, 2, 3, 4, 5])

In [51]:
slice_of_arr[:] = 99

In [54]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [56]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [61]:
arr_copy = arr.copy()

In [62]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [64]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [66]:
arr_copy[:] = 100

In [68]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [70]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [72]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [74]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [79]:
arr_2d[0][0]

np.int64(5)

In [81]:
arr_2d[0,0]

np.int64(5)

In [83]:
arr_2d[0]

array([ 5, 10, 15])

In [85]:
arr_2d[2][1]

np.int64(40)

In [87]:
arr_2d[1,2]

np.int64(30)

In [89]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [97]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [99]:
arr_2d[1:2,:]

array([[20, 25, 30]])

In [100]:
arr_2d[2:,]

array([[35, 40, 45]])

In [103]:
arr = np.arange(1,11)

In [105]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])