In [3]:
my_list = [1,2,3]

In [1]:
import numpy as np

In [6]:
arr = np.array(my_list)

In [10]:
my_mat = [[1,2,3], [4,5,6],[7,8,9]]

In [12]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [17]:
np.zeros(3)

array([0., 0., 0.])

In [22]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones(4)

array([1., 1., 1., 1.])

In [32]:
np.linspace(0,5,8)

array([0.        , 0.71428571, 1.42857143, 2.14285714, 2.85714286,
       3.57142857, 4.28571429, 5.        ])

In [36]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [39]:
np.random.rand(5)

array([0.95230596, 0.54947579, 0.78153374, 0.76530643, 0.41846008])

In [41]:
np.random.rand(5,5)

array([[0.99256478, 0.54548005, 0.43262583, 0.63708063, 0.93013729],
       [0.95684176, 0.51000565, 0.19220055, 0.96965066, 0.901203  ],
       [0.46216739, 0.81547061, 0.54163853, 0.63792423, 0.16886686],
       [0.27862966, 0.31779705, 0.65163381, 0.34192066, 0.57006903],
       [0.06437667, 0.93274262, 0.45873723, 0.49458114, 0.18105302]])

In [45]:
np.random.randn(5,5)

array([[-0.07069164,  0.26408802,  0.06183803, -1.09274629,  0.7507873 ],
       [-1.52450922,  0.44386528, -1.44721156, -0.4338553 ,  0.41045411],
       [ 0.81521813,  0.30952992, -1.88746016,  0.70641235,  0.89819744],
       [ 0.69422815, -2.24553374,  0.3718718 , -1.14834683, -0.3099503 ],
       [-0.48770628,  0.56846354, -1.01253163, -0.09841078, -0.41752117]])

In [64]:
np.random.randint(1,100,100)

array([55, 54, 63, 87, 75, 68, 94, 86, 77, 28, 39, 13, 55, 42,  6, 97, 18,
       38,  8, 74, 51,  2, 65,  3, 97,  9, 36,  8, 34, 97, 27, 21, 95,  2,
       18, 64, 56, 16, 57, 45, 94, 71, 19, 19, 61, 56, 57, 47, 16, 72, 40,
       39, 27, 79, 82, 35, 34, 49,  3, 22, 26, 35, 62, 25, 38, 30,  2, 22,
       10, 64, 12, 68, 90, 61, 77, 42, 26, 15, 15, 30, 70, 83, 53, 94, 23,
        3, 30, 75, 64, 28, 93,  7, 47, 41, 74, 21, 74, 73, 10, 31])

In [66]:
arr = np.arange(25)

In [70]:
ranarr = np.random.randint(0,50,10)

In [74]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [78]:
ranarr.max()

np.int64(49)

In [81]:
ranarr.min()

np.int64(1)

In [83]:
ranarr.argmax()

np.int64(0)

In [85]:
ranarr.dtype

dtype('int64')